# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

 # Force dep to vendor the code generators, which aren't imported just used at dev time.
 # Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/apache/thrift/lib/go/thrift",
  "github.com/m3db/stackmurmur3",
  "github.com/m3db/bloom",
  "github.com/coreos/bbolt",
  "github.com/m3db/vellum/regexp",
  "github.com/m3db/vellum/utf8",
  "github.com/golang/mock/gomock",
  "github.com/golang/mock/mockgen",
  "github.com/kubernetes/utils/pointer",
  "github.com/rakyll/statik/fs",
]

[[constraint]]
name = "github.com/kubernetes/utils"
branch = "master"

[[override]]
name = "github.com/golang/mock"
version = "1"

[[override]]
name = "github.com/m3db/stackmurmur3"
revision = "744c0229c12ed0e4f8cb9d081a2692b3300bf705"

[[override]]
name = "github.com/coreos/bbolt"
revision = "32c383e75ce054674c53b5a07e55de85332aee14"

[[override]]
name = "github.com/m3db/bloom"
revision = "47fe1193cdb900de7193d1f3d26ea9b2cbf6fb31"

[[override]]
name = "github.com/couchbase/vellum"
revision = "51c732079c882f52f8e6af889d99ac2a1611d5e4"
source = "github.com/m3db/vellum"

[[constraint]]
name = "github.com/m3db/m3"
version = "0.8.1"

[[override]]
name = "github.com/apache/thrift"
version = "0.9.3-pool-read-binary-2"
source = "github.com/m3db/thrift"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/client-go"
  branch = "release-9.0"

[[constraint]]
name = "github.com/rakyll/statik"
version = "0.1.5"

[[constraint]]
name = "github.com/pkg/errors"
version = "0.8.1"

# We pin Jaeger deps to same revisions as m3 does
[[override]]
name = "github.com/uber/jaeger-lib"
version = "^1.5.0"

[[override]]
name = "github.com/uber/jaeger-client-go"
version = "^2.7.0"

[[override]]
name = "github.com/opentracing-contrib/go-stdlib"
revision = "77df8e8e70b403c6b13c0fffaa4867c9044ff4e9"

[[constraint]]
name = "github.com/uber-go/tally"
version = "3.3.8"

[[override]]
name = "github.com/m3db/prometheus_client_golang"
revision = "8ae269d24972b8695572fa6b2e3718b5ea82d6b4"
[[override]]
name = "github.com/m3db/prometheus_client_model"
revision = "8b2299a4bf7d7fc10835527021716d4b4a6e8700"
[[override]]
name = "github.com/m3db/prometheus_common"
revision = "25aaa3dff79bb48116615ebe1dea6a494b74ce77"
[[override]]
name = "github.com/m3db/prometheus_procfs"
revision = "1878d9fbb537119d24b21ca07effd591627cd160"
