apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: m3db.m3db.github.io
spec:
  group: m3db.github.io
  names:
    kind: M3DB
    listKind: M3DBList
    plural: m3db
    singular: m3db
  scope: Namespaced
  version: v1alpha1
